const TOKEN_TYPE_ID = 0;
const TOKEN_VALUE_ID = 1;
const TOKEN_LINE_ID = 2;
const TOKEN_COLUMN_ID = 3;

const TOKEN_TYPE_WORD = 'word';
const TOKEN_TYPE_TAG = 'tag';
const TOKEN_TYPE_ATTR_NAME = 'attr-name';
const TOKEN_TYPE_ATTR_VALUE = 'attr-value';
const TOKEN_TYPE_SPACE = 'space';
const TOKEN_TYPE_NEW_LINE = 'new-line';

module.exports = {
    TYPE_ID: TOKEN_TYPE_ID,
    VALUE_ID: TOKEN_VALUE_ID,
    LINE_ID: TOKEN_LINE_ID,
    COLUMN_ID: TOKEN_COLUMN_ID,
    TYPE_WORD: TOKEN_TYPE_WORD,
    TYPE_TAG: TOKEN_TYPE_TAG,
    TYPE_ATTR_NAME: TOKEN_TYPE_ATTR_NAME,
    TYPE_ATTR_VALUE: TOKEN_TYPE_ATTR_VALUE,
    TYPE_SPACE: TOKEN_TYPE_SPACE,
    TYPE_NEW_LINE: TOKEN_TYPE_NEW_LINE
};