name: Running Code Coverage

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 2

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install Codecov
      run: npm install -g codecov

    - name: Install dependencies
      run: npm install

    - name: Bootstrap packages
      run: npm run bootstrap

    - name: Run the lint
      run: npm run lint

    - name: Run the tests
      run: npm run test

    - name: Run the coverage
      run: npm run cover

    - name: Run the coverage
      run: codecov
